apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: 218306567362.dkr.ecr.ap-south-1.amazonaws.com/python/smruti-python
        ports:
        - containerPort: 5000

